models/OrderCode.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "order_code".
 *
 * @property int $id
 * @property string|null $order_code
 * @property string|null $created_date
 * @property int|null $stage
 * @property int|null $client_id
 * @property string|null $order_date
 * @property int|null $address_id
 * @property int|null $delivery_price
 * @property int|null $delivery
 * @property string|null $description
 * @property string|null $description_ru
 * @property int|null $pay
 * @property int|null $billing_status
 * @property int|null $bot
 */
class OrderCode extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_code';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_date', 'order_date'], 'safe'],
            [['stage', 'client_id', 'address_id', 'delivery_price', 'delivery', 'pay', 'billing_status', 'bot'], 'default', 'value' => null],
            [['stage', 'client_id', 'address_id', 'delivery_price', 'delivery', 'pay', 'billing_status', 'bot'], 'integer'],
            [['description', 'description_ru'], 'string'],
            [['order_code'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_code' => 'Order kodi',
            'created_date' => 'Buyurtma qilingan sana',
            'stage' => 'Etap',
            'client_id' => 'client ismi',
            'order_date' => 'Order Date',
            'address_id' => 'Address ID',
            'delivery_price' => 'Delivery Price',
            'delivery' => 'Delivery',
            'description' => 'Description',
            'description_ru' => 'Description Ru',
            'pay' => 'Pay',
            'pay' => 'To`lov turi',
            'file_id' => 'file id',
            'billing_status' => 'To`lov holati',
            'bot' => 'Bot',
        ];
    }
    public function getOrders()
    {
        return $this->hasMany(ArriveOrders::class, ['order_code_id' => 'order_code']);
    }
    public function getAddress()
    {
        return $this->hasOne(OrderAddress::className(), ['order_code_id' => 'order_code']);
    }
    public function getClient()
    {
        return $this->hasOne(Clients::className(), ['id' => 'client_id']);
    }
    public function getTotal()
    {
        $order_code = $this->order_code;
        $model = ArriveOrders::find()->where("order_code_id = :order_code",[":order_code"=>$order_code])->sum("sell_price");
        return $model;
    }
    public function getRegion()
    {
        return $this->hasOne(Region::className(), ['id' => 'region_id']);
        // return $model->title_uz;
    }

    public function getCamment()
    {
        return $this->hasOne(ClientOrderCamments::className(), ['order_code_id' => 'id']);
        // return $model->title_uz;
    }
    
}

models/Products.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property int|null $sub_category_id
 * @property string|null $title_uz
 * @property string|null $title_ru
 * @property int|null $price
 * @property string|null $img
 * @property string|null $description_uz
 * @property string|null $description_ru
 * @property int|null $status
 */

class Products extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    
    const LIMIT_PRODUCT = 12;
    public $imageFile;

   
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    
    public function rules()
    {
        return [
            [['title_uz', 'title_ru','price'], 'required'],
            [['sub_category_id', 'price', 'status'], 'default', 'value' => null],
            [['price', 'status', 'count','quantity','main_category'], 'integer'],
            [['dollar'], 'double'],
            [['description_uz', 'description_ru','description_en'], 'string'],
            [['title_uz', 'title_ru', 'img','title_en','link','made','made_ru','made_uz','sku','sku_api'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */

    public function attributeLabels()
    {
        return [
            'sub_category_id' => 'Kategoriya raqami',
            'title_uz' => 'Mahsulot nomi',
            'title_ru' => 'Mahsulot nomi ru',
            'price' => 'Narxi',
            'img' => 'Rasmi',
            'description_uz' => 'Tavsifi',
            'description_ru' => 'Tavsifi Ru',
            'status' => 'Status',
            'count' => 'Soni',
        ];
    }
    
    public function getSubCategory()
    {
           return $this->hasOne(SubCategory::className(), ['id' => 'sub_category_id']);
    }

    public function getCategory()
    {
      return $this->hasOne(Category::className(), ['id' => 'main_category']);
    }

    public function getDropdown()
    {
      return SubCategory::find()->all();
    }

    public function getImgs()
    {
      return $this->hasMany(ProductImg::className(),["product_id" => "id"])->limit(3);
    }

    public function getProductimg()
    {
      return  ProductImg::find()->where("product_id = :product_id",[":product_id" => $this->id])->orderBy(["id" => SORT_ASC])->all();
      
    }
    
    public function getColor() 
    {
      return $this->hasMany(ProductDetailsCode::class,["product_id" => "id"]);
    }
    
    public static function getByDetailId($detail_id,$id)
    {
        if (!$product_detail = ProductDetailsCode::find()->where(['product_id' => $id,'detail_id' => $detail_id])->all()){
            return [0];
        }
        return $product_detail;
    }

    public function getSale()
    {
      $current_date = date("Y-m-d H:i:s");
      $sql = "SELECT * FROM product_sale WHERE product_id = ".$this->id." and  enter_date <= '".$current_date."' and end_date >= '".$current_date."'";
      $model = ProductSale::findBySql($sql)->one();
      return $model;
      // return  $this->hasOne(ProductSale::className(), ['product_id' => 'id']);
    }

    public function getStars() 
    {
        $sql = "select sum(star) , count(id) from reviews where product_id = ".$this->id;
        $model = Yii::$app->db->createCommand($sql)->queryAll();
        $sum = $model[0]["sum"];
        $count = $model[0]["count"];
        $stars = 0;
        if ($sum > 0 and $count > 0) {
            $stars = $sum / $count;
        }
        return round($stars);
    }

    public static function hasProduct() 
    {
        $session = Yii::$app->session;
        $last_id =  $session["list"]["last_id"];
            // $product = Products::find()->where("id > :id",[":id" => $last_id])->limit(self::LIMIT_PRODUCT)->all();
        $str =  $session["list"]["search_key"];
        $whereType = "";
        if (isset($session["list"]["search_type"]) and !empty($session["list"]["search_type"])) {
            $status = 0;
            $status2 = 0;
            if ($session["list"]["search_type"] == "trend") {
                $status = 2;
                $status2 = 4;
                $session["list"]["select_search"] = 2;
            }  else if ($session["list"]["search_type"] == "new") {
                $status = 4;
                $status2 = 3;
                $session["list"]["select_search"] = 1;
            }  
            if ($status != 0 and $status2 != 0) {
                $whereType = "where T.status = ".$status. " or T.status = ".$status2;
            }
        }
        
        if ((isset($session["list"]["search_type"]) and !empty($session["list"]["search_type"])) and $session["list"]["search_type"] == "price") {
            $sql = "
                SELECT 
                  * 
                from 
                  (
                    SELECT 
                      pr.* 
                    FROM 
                      category as ct 
                      inner join products as pr on ct.id = pr.main_category
                      inner join product_sale as ps on ps.product_id = pr.id and  ps.enter_date <= now() and ps.end_date >= now()
                    where 
                      (
                        lower(ct.title_uz) like '%".$str."%' 
                        or lower(ct.title_ru) like '%".$str."%'
                      ) 
                      and pr.id > ".$last_id." 
                    union 
                    select 
                      pr.* 
                    from 
                      sub_category as sc 
                      inner join sub_category as sc2 on sc.id = sc2.sub_category_id 
                      inner join products as pr on sc.id = pr.sub_category_id or sc2.id = pr.sub_category_id 
                      inner join product_sale as ps on ps.product_id = pr.id and  ps.enter_date <= now() and ps.end_date >= now()
                    where 
                      (
                        (
                          lower(sc.title_uz) like '%".$str."%' 
                          or lower(sc.title_ru) like '%".$str."%'
                        ) 
                        or (
                          lower(sc2.title_uz) like '%".$str."%' 
                          or lower(sc2.title_ru) like '%".$str."%'
                        )
                      ) 
                      and pr.id > ".$last_id." 
                    union 
                    select 
                      pr.* 
                    from 
                      products as pr 
                    inner join product_sale as ps on ps.product_id = pr.id and  ps.enter_date <= now() and ps.end_date >= now()
                    where 
                      (
                        lower(pr.title_uz) like '%".$str."%' 
                        or lower(pr.title_ru) like '%".$str."%'
                      ) 
                      and pr.id > ".$last_id."
                  ) as T 
                group by 
                  T.id, 
                  T.sub_category_id, 
                  t.main_category, 
                  T.sell_count, 
                  T.title_uz, 
                  T.title_ru, 
                  T.price, 
                  T.img, 
                  T.description_uz, 
                  T.description_ru, 
                  T.status, 
                  T.count, 
                  T.type, 
                  T.view, 
                  T.sku, 
                  T.made, 
                  T.dollar, 
                  T.sold_product, 
                  T.quantity
            ";
        } else {
            $sql = "
                SELECT 
                  * 
                from 
                  (
                    SELECT 
                      pr.* 
                    FROM 
                      category as ct 
                      inner join products as pr on ct.id = pr.main_category 
                    where 
                      (
                        lower(ct.title_uz) like '%".$str."%' 
                        or lower(ct.title_ru) like '%".$str."%'
                      ) 
                      and pr.id > ".$last_id." 
                    union 
                    select 
                      pr.* 
                    from 
                      sub_category as sc 
                      inner join sub_category as sc2 on sc.id = sc2.sub_category_id 
                      inner join products as pr on sc.id = pr.sub_category_id 
                      or sc2.id = pr.sub_category_id 
                    where 
                      (
                        (
                          lower(sc.title_uz) like '%".$str."%' 
                          or lower(sc.title_ru) like '%".$str."%'
                        ) 
                        or (
                          lower(sc2.title_uz) like '%".$str."%' 
                          or lower(sc2.title_ru) like '%".$str."%'
                        )
                      ) 
                      and pr.id > ".$last_id." 
                    union 
                    select 
                      pr.* 
                    from 
                      products as pr 
                    where 
                      (
                        lower(pr.title_uz) like '%".$str."%' 
                        or lower(pr.title_ru) like '%".$str."%'
                      ) 
                      and pr.id > ".$last_id."
                  ) as T 
                ".$whereType."
                group by 
                  T.id, 
                  T.sub_category_id, 
                  t.main_category, 
                  T.sell_count, 
                  T.title_uz, 
                  T.title_ru, 
                  T.price, 
                  T.img, 
                  T.description_uz, 
                  T.description_ru, 
                  T.status, 
                  T.count, 
                  T.type, 
                  T.view, 
                  T.sku, 
                  T.made, 
                  T.dollar, 

views/site/add_cashback_modal.php
<div class="form-group">
    <label class="control-label" for="cashback_parcent">Cashback foizi</label>
    <?php if ($value_cashback != 0): ?>
        <input type="integer" value="<?php echo $value_cashback ?>" id="cashback_parcent" class="form-control">
    <?php else: ?>        
        <input type="integer" id="cashback_parcent" class="form-control">
    <?php endif ?>
    <small class='hidden cashback_error'>Maydon bo`sh bo`lishi mumkin emas</small>
    <br>
    <div class="help-block"></div>
</div>
<style type="text/css">
    .hidden{
        display: none;
    }
    .name_error {
        color: red;
        font-size:15px;

    }
    .name_error_ru {
        color: red;
        font-size:15px;
        
    }
    .border-red{
        border:1px solid red;
        border-radius:3px;
    }

</style>

views/site/checkout.php
<?php  
	use yii\helpers\Url;
?>
<div class="holder breadcrumbs-wrap mt-0">
	<div class="container">
		<ul class="breadcrumbs">
			<li>
				<a href="<?php echo Url::toRoute('site/index')?>">
					<?php echo Yii::t('app', 'home'); ?>
				</a>
			</li>
			<li>
				<span>
					<?php echo Yii::t('app', 'checkout'); ?>	
				</span>
			</li>
		</ul>
	</div>
</div>
<div class="holder">
	<div class="container">
		<h1 class="text-center">
			<?php echo Yii::t('app', 'order_checkout'); ?>	
		</h1>
		<div class="row">
			<div class="col-md-9">
				<div class="card">
					<div class="card-body">
						<h2>
							<?php echo Yii::t('app', 'my_address'); ?>	
						</h2>
						<div class="row">
							<div class="col">
								<?php if (isset($client_address) && !empty($client_address)): ?>
									<?php foreach ($client_address as $key => $value): ?>
										<div class="clearfix border p-1">
											<input id="formcheckoutRadio<?php echo $value->id ?>" value="<?php echo $value->id ?>" name="address" type="radio" class="address">
											<label for="formcheckoutRadio<?php echo $value->id ?>" class="w-100">
												<p class="m-0">
													<?php echo $value->address ?>
												</p>
												<small class="text-muted">
													<?php if (Yii::$app->language == 'uz'): ?>
														<?php echo $value->region->title_uz ?>	
													<?php else: ?>
														<?php echo $value->region->title_ru ?>
													<?php endif ?>
												</small>
											</label>
										</div>
										<br>
									<?php endforeach ?>
								<?php else: ?>
									<?php echo Yii::t('app', 'not_address'); ?>	
								<?php endif ?>
								
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-9 mt-2 mt-md-0">
				<div class="card">
					<div class="card-body">
						<h2>
							<?php echo Yii::t('app', 'address'); ?>	
						</h2>
						<label>
							<?php echo Yii::t('app', 'districts'); ?>:
						</label>
						<div class="form-group select-wrapper">
							<select class="form-control form-control--sm" id="region">
								<?php if (isset($regions) && !empty($regions)): ?>
									<?php foreach ($regions as $key => $value): ?>
										<option value="<?php echo $value->id ?>">
											<?php if (Yii::$app->language == 'uz'): ?>
												<?php echo $value->title_uz ?>
											<?php else: ?>
												<?php echo $value->title_ru ?>
											<?php endif ?>
										</option>		
									<?php endforeach ?>
								<?php endif ?>
								
							</select>
						</div>
						<div class="mt-2"></div>
						<label>
							<?php echo Yii::t('app', 'address2'); ?>:
						</label>
						<div class="form-group">
							<input type="text" class="form-control form-control--sm" id="new_address">
						</div>
						<div class="clearfix">
							<label for="formcheckoutCheckbox1">
								<?php echo Yii::t('app', 'add_to_my_address'); ?>
							</label>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="mt-3"></div>
		<h2 class="custom-color">
			<?php echo Yii::t('app', 'order_summary'); ?>	
		</h2>
		<div class="row">
			<div class="col-md-12">
				<div class="cart-table cart-table--sm pt-3 pt-md-0">
					<div class="cart-table-prd cart-table-prd--head py-1 d-none d-md-flex">
						<div class="cart-table-prd-image text-center">
							<?php echo Yii::t('app', 'img'); ?>
						</div>
						<div class="cart-table-prd-content-wrap">
							<div class="cart-table-prd-info">
								<?php echo Yii::t('app', 'name_product'); ?>
							</div>
							<div class="cart-table-prd-qty">
								<?php echo Yii::t('app', 'qty'); ?>
							</div>
							<div class="cart-table-prd-price">
								<?php echo Yii::t('app', 'price'); ?>
							</div>
						</div>
					</div>

					<?php if (isset($_SESSION['cart']) && !empty($_SESSION['cart'])): ?>
						<?php foreach ($_SESSION['cart'] as $key => $value): ?>
							<div class="cart-table-prd">
								<div class="cart-table-prd-image">
									<a href="#" class="prd-img">
										<img class="lazyload fade-up" src="<?php echo $value['img'] ?>" data-src="<?php echo $value['img'] ?>" alt="">
									</a>
								</div>
								<div class="cart-table-prd-content-wrap">
									<div class="cart-table-prd-info">
										<h2 class="cart-table-prd-name">
											<a href="product.html">
												<?php if (Yii::$app->language == "uz"): ?>
													<?php echo $value['title_uz'] ?>
												<?php else: ?>
													<?php echo $value['title_ru'] ?>
												<?php endif ?>
											</a>
										</h2>
									</div>
									<div class="cart-table-prd-qty">
										<div class="qty qty-changer">
											<input disabled readonly type="text" class="qty-input disabled" value="<?php echo $value['count'] ?>">
										</div>
									</div>
									<div class="cart-table-prd-price-total">
										<?php echo price($value['total_price']) ?>
									</div>
								</div>
							</div>
						<?php endforeach ?>
					<?php endif ?>
					
					
				</div>
			</div>
			<div class="col-md-6 mt-2 mt-md-0">
				<div class="card">
					<div class="card-body">
						<h2>
							<?php echo Yii::t('app', 'payment_method'); ?>	
						</h2>
						<div class="clearfix">
							<input id="formcheckoutRadio4" value="1" name="payment" type="radio" class="pay" checked="checked">
							<label for="formcheckoutRadio4">Click</label>
						</div>
					</div>
				</div>
				<div class="mt-2"></div>
				<div class="cart-total-sm">
					<span>
						<?php echo Yii::t("app","sub_total") ?>
					</span>
					<span class="card-total-price">
						<?php echo price($_SESSION['cart_tl_price']) ?>
					</span>
				</div>
				<div class="clearfix mt-2">
					<button id="place_order" type="submit" class="btn btn--lg w-100">
						<?php echo Yii::t('app', 'place_order'); ?>	
					</button>
				</div>
				<div class="clearfix mt-2">
					<a href="<?php echo Url::toRoute('site/cart')?>" class="btn btn--grey btn-block">
						<?php echo Yii::t("app","back_cart") ?>
					</a>
				</div>
				
			</div>
		</div>
	</div>
</div>

views/site/form_contact.php
<div class="modal-info-heading">
    <div class="mb-1"><i class="icon-envelope"></i></div>
    <h2><?php echo Yii::t("app","ask_question"); ?></h2>
</div>
<form class="contact_form">
    <div class="form-group">
        <input id="name_contact" type="text" name="Contact[name]" class="form-control form-control--sm"
               placeholder="<?php echo Yii::t("app","name") ?>">
        <p class="name_error d-none" style="color:red;"><?php echo Yii::t("app","name_error") ?></p>
    </div>
    <div class="form-group">
<!--                                         <input  type="text" name="Contact[phone]" class="form-control form-control--sm"
               placeholder="<?php echo Yii::t("app",'phone_number') ?>"> -->
        <input name="Contact[phone]" autocomplete="off" class="form-control js-phone-mask" id="phone_number_contact" data-tel="+998" value="+998" placeholder="<?php echo Yii::t('app', 'phone_number'); ?>">
        <p class="phone_number_error d-none" style="color:red;"><?php echo Yii::t("app","phone_number_error") ?></p>
    </div>
    <div class="form-group">
        <textarea id="message_contact" class="form-control textarea--height-170" name="Contact[body]" placeholder="<?php echo Yii::t("app","question_message") ?>" required=""></textarea>
        <p class="message_error d-none" style="color:red;"><?php echo Yii::t("app","message_error") ?></p>
    </div>
    <a class="btn send_question"><?php echo Yii::t("app","send_sms") ?></a>
    <p class="p--small mt-15 mb-0"><?php echo Yii::t("app","contacting") ?></p><input
        name="recaptcha-v3-token" type="hidden">
</form>

views/site/message_success.php
<div class="d-flex flex-column justify-content-center align-items-center">
	<h2><?php echo Yii::t("app","message_success") ?></h2>
	<img src="https://c.tenor.com/Hw7f-4l0zgEAAAAM/check-green.gif" alt="">
</div>

views/site/product_more.php
<?php 

    use app\models\Products;
    use app\models\ProductDetailsCode;

?>
<?php foreach ($product_search as $key => $value): ?>
    <?php $product_block = Products::getByDetailId($color_id,$value["id"]); ?>
    <div class="prd prd--style2 prd-labels--max prd-labels-shadow" style="opacity:1;">
        <div class="prd-inside">
            <div class="prd-img-area">
                <a href="product.html" class="prd-img image-hover-scale image-container">
                    <img src="data:<?php echo $value["img"] ?>" data-src="<?php echo $value["img"] ?>" alt="Oversized Cotton Blouse" class="js-prd-img lazyload fade-up">
                    <div class="foxic-loader"></div>
                    <div class="prd-big-squared-labels">
                        
                        <?php if ($value["status"] == 3 or $value["status"] == 4): ?>
                            <div class="label-new">
                                <span>
                                    <?php if (Yii::$app->language == 'uz'): ?>
                                        Yangi
                                    <?php else: ?>
                                        Новый
                                    <?php endif ?>
                                </span>
                            </div>
                        <?php endif ?>
                        <?php $sale_product = $value->sale; ?>
                        <?php if (isset($sale_product) and !empty($sale_product)): ?>
                            
                            <div class="label-sale">
                                <span><?php echo "-".round($sale_product["sale_pracent"])."%" ?>
                                    <span class="sale-text">
                                        <?php if (Yii::$app->language == 'uz'): ?>
                                            Chegirma
                                        <?php else: ?>
                                            Скидка
                                        <?php endif ?>
                                    </span>
                                </span>
                                
                                <div class="countdown-circle">
                                    <div class="countdown js-countdown" data-countdown="2021/07/01"></div>
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                </a>
                <div class="prd-circle-labels">
                    <a href="#" class="circle-label-compare circle-label-wishlist--add js-add-wishlist mt-0" title="Add To Wishlist"><i class="icon-heart-stroke"></i></a><a href="#" class="circle-label-compare circle-label-wishlist--off js-remove-wishlist mt-0" title="Remove From Wishlist"><i class="icon-heart-hover"></i></a>
                    <a href="#" class="circle-label-qview js-prd-quickview prd-hide-mobile" data-src="ajax/ajax-quickview.html"><i class="icon-eye"></i><span>QUIsK VIEW</span></a>
                    <?php if (count($product_block) > 1): ?>
                        <div class="colorswatch-label colorswatch-label--variants js-prd-colorswatch">
                            <i class="icon-palette"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span><span class="path5"></span><span class="path6"></span><span class="path7"></span><span class="path8"></span><span class="path9"></span><span class="path10"></span></i>
                            <ul>
                                <?php foreach ($product_block as $key2 => $value2): ?>
                                    <?php $product_img = ProductDetailsCode::MultiDetails($value2["product_id"],$value2["multi_detail_id"]); ?>
                                    <li data-image="<?php if (isset($product_img)): ?><?php echo $product_img->img ?><?php endif ?>">
                                        <a style="background: <?php echo $value2->multi_one->color_name; ?>;" class="js-color-toggle" data-toggle="tooltip" data-placement="left" title="Color Name">
                                            <!-- <img src="asset/images/colorswatch/color-green.png" alt=""> -->
                                        </a>
                                    </li>
                                <?php endforeach ?>
                                
                            </ul>
                        </div>
                    <?php endif ?>
                </div>

                
                <ul class="list-options color-swatch">
                    <?php $i = 1; ?>
                    <?php foreach ($value->imgs as $key2 => $value2): ?>
                        <?php if ($i == 1): ?>
                            <li data-image="<?php echo$value2["img"]  ?>" class="active"><a href="#" class="js-color-toggle" data-toggle="tooltip" data-placement="right" title="Color Name"><img src="data:<?php echo$value2["img"]  ?>" data-src="<?php echo$value2["img"]  ?>" class="lazyload fade-up" alt="Color Name"></a></li>
                        <?php else: ?>
                            <li data-image="<?php echo$value2["img"]  ?>" class=><a href="#" class="js-color-toggle" data-toggle="tooltip" data-placement="right" title="Color Name"><img src="data:<?php echo$value2["img"]  ?>" data-src="<?php echo$value2["img"]  ?>" class="lazyload fade-up" alt="Color Name"></a></li>

                        <?php endif ?>
                        <?php $i++; ?>
                    <?php endforeach ?>

                </ul>
            </div>
            <div class="prd-info">
                <div class="prd-info-wrap">
                    <div class="prd-info-top">
                        <div class="prd-rating"><i class="icon-star-fill fill"></i><i class="icon-star-fill fill"></i><i class="icon-star-fill fill"></i><i class="icon-star-fill fill"></i><i class="icon-star-fill fill"></i></div>
                    </div>
                    <?php $stars =  $value->stars; ?>
                    <div class="prd-rating justify-content-center">
                        <?php for ($i = 1; $i <= $stars; $i++): ?>
                            <i class="icon-star-fill fill"></i>
                        <?php endfor ?>
                    </div>
                    <div class="prd-tag"><a href="#">
                        <?php if (Yii::$app->language == "uz"): ?>
                                <?php echo $value->subCategory->title_uz ?>
                            <?php else: ?>
                                <?php echo $value->subCategory->title_ru ?>
                        <?php endif ?>
                    </a></div>
                    <h2 class="prd-title"><a href="product.html">
                        <?php if (Yii::$app->language == "uz"): ?>
                            <?php echo $value["title_uz"] ?>
                        <?php else: ?>
                            <?php echo $value["title_ru"] ?>
                        <?php endif ?>
                    </a></h2>
                    <div class="prd-description">
                        Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante sed lacinia.
                    </div>
                    <div class="prd-action">
                        <form action="#">
                            <button class="btn js-prd-addtocart" data-product='{"name": "Oversized Cotton Blouse", "path":"images/skins/fashion/products/product-03-1.jpg", "url":"product.html", "aspect_ratio":0.778}'>
                                <?php echo Yii::t('app', 'add_to_cart'); ?>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="prd-hovers">
                    <div class="prd-circle-labels">
                        <div><a href="#" class="circle-label-compare circle-label-wishlist--add js-add-wishlist mt-0" title="Add To Wishlist"><i class="icon-heart-stroke"></i></a><a href="#" class="circle-label-compare circle-label-wishlist--off js-remove-wishlist mt-0" title="Remove From Wishlist"><i class="icon-heart-hover"></i></a></div>
                        <div class="prd-hide-mobile"><a href="#" class="circle-label-qview js-prd-quickview" data-src="ajax/ajax-quickview.html"><i class="icon-eye"></i><span>QUICK VIEW</span></a></div>
                    </div>
                    <div class="prd-price">
                        <?php $product_sale = $value->sale; ?>
                        <?php if (isset($product_sale) and !empty($product_sale)): ?>
                            <div class="price-old"><?php echo $value["price"] ?></div>
                            
                            <div class="price-new"><?php echo $product_sale["sale_price"] ?></div>
                            
                            <?php else: ?>
                            <div class="price-new"><?php echo $value["price"] ?></div>
                        <?php endif ?>
                    </div>
                    <div class="prd-action">
                        <div class="prd-action-left">
                            <form action="#">
                                <button class="btn js-prd-addtocart" data-product='{"name": "Oversized Cotton Blouse", "path":"images/skins/fashion/products/product-03-1.jpg", "url":"product.html", "aspect_ratio":0.778}'>
                                <?php echo Yii::t('app', 'add_to_cart'); ?>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach ?>