models/ProductSale.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "product_sale".
 *
 * @property int $id
 * @property int|null $product_id
 * @property int|null $sale_price
 * @property int|null $sale_pracent
 * @property string|null $enter_date
 * @property string|null $end_date
 */
class ProductSale extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product_sale';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['product_id', 'sale_price','sale_dollar'], 'required'],
            [['product_id', 'sale_price',], 'integer'],
            [['enter_date', 'end_date'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Mahsulot nomi',
            'sale_price' => 'Chegirma summasi',
            'sale_pracent' => 'Chegirma foizi',
            'enter_date' => 'Chegirma boshlanish vaqti',
            'end_date' => 'Chegirma tugash vaqti',
        ];
    }

    public function getProduct()
    {
        return $this->hasOne(Products::className(), ['id' => 'product_id']);
    }   
    
}

controllers/ProductSaleController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ProductSale;
use app\models\Products;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProductSaleController implements the CRUD actions for ProductSale model.
 */
class ProductSaleController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ProductSale models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ProductSale::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ProductSale model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProductSale model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductSale();
        $products = Products::find()->where(["status" => 1])->all();
        $current_date = date("Y-m-d h:i");
        if ($model->load(Yii::$app->request->post())) {
            $post = Yii::$app->request->post();
            $product_id = $post["ProductSale"]["product_id"];
            $sale_price = $post["ProductSale"]["sale_price"];
            $enter_date = $post["Section"]["product_sale"]["enter_date"];
            $end_date = $post["Section"]["product_sale"]["end_date"];
            $product = Products::find()->where('id = :id' ,[":id" => $product_id])->one();
            if (isset($product) and !empty($product)) {
                $price_product = $product->price;
                if ($sale_price > $price_product) {
                    Yii::$app->session->setFlash('danger', "Chegirma narxi mahsulot narxidan katta bo`lishi kerak emas!");
                    return $this->redirect(Yii::$app->request->referrer);
                } else if ($sale_price < 0) {
                    Yii::$app->session->setFlash('danger', "Chegirma narxi 0dan kichik bo`lishi mumkin emas!");
                    return $this->redirect(Yii::$app->request->referrer);
                } else if ($enter_date < $current_date or $end_date < $current_date) {
                    Yii::$app->session->setFlash('danger', "Chegirma boshlanish va tugash vaqti hozirgi vaqtdan katta bo`lishi kerak");
                    return $this->redirect(Yii::$app->request->referrer);
                } else if ($end_date < $enter_date) {
                    Yii::$app->session->setFlash('danger', "Chegirma boshlanish vaqti  tugash vaqtidan keyin bo`lmasligi kerak!");
                    return $this->redirect(Yii::$app->request->referrer);
                } else {
                    $sale_product = Products::findOne($product_id);
                    $product_price = $sale_product["price"];
                    $one_pracent = $product_price / 100;
                    // echo $one_pracent;
                    $sale_pracent = 100 - ($sale_price / $one_pracent);
                    $model->product_id = $product_id;
                    $model->sale_price = $sale_price;
                    $model->sale_pracent = $sale_pracent;
                    $model->enter_date = $enter_date;
                    $model->end_date = $end_date;
                    if ($model->save()) {
                        return $this->redirect(['index']);
                    } else {
                        print_r($model->errors);
                        die();
                    }

                }
            }
        }


        return $this->render('create', [
            'model' => $model,
            'products' => $products
        ]);
    }

    /**
     * Updates an existing ProductSale model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $products = Products::find()->where("status != :status",["status" => 2])->all();
        if ($model->load(Yii::$app->request->post())) {
            $post = Yii::$app->request->post();
            $product_id = $post["ProductSale"]["product_id"];
            $sale_price = $post["ProductSale"]["sale_price"];
            $enter_date = $post["Section"]["product_sale"]["enter_date"];
            $end_date = $post["Section"]["product_sale"]["end_date"];
            $sale_product = Products::findOne($product_id);
            $product_price = $sale_product["price"];
            $one_pracent = $product_price / 100;
            // echo $one_pracent;
            $sale_pracent = 100 - ($sale_price / $one_pracent);
            $model->product_id = $product_id;
            $model->sale_price = $sale_price;
            $model->sale_pracent = $sale_pracent;
            $model->enter_date = $enter_date;
            $model->end_date = $end_date;
            if ($model->save()) {
                return $this->redirect(['index']);
            } else {
                print_r($model->errors);
                die();
            }
        }

        return $this->render('update', [
            'model' => $model,
            'products' => $products
        ]);
    }

    /**
     * Deletes an existing ProductSale model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionFind()
    {
        if (Yii::$app->request->isAjax) {
            \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
            
            $id = intval($_GET['input']);

            $model = Products::findOne($id);

            if (isset($model)) {
                return [
                    'status' => 'success',
                    'sum' => $model->price,
                    'dollar' => $model->dollar
                 ];    
            }
            

        }
    }

    /**
     * Finds the ProductSale model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ProductSale the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProductSale::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/product-sale/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use kartik\datetime\DateTimePicker;

/* @var $this yii\web\View */
/* @var $model app\models\ProductSale */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-sale-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-6">
            <?=$form->field($model, 'product_id')->label('Mahsulot nomi')->widget(Select2::classname(),
                [
                    'data' => ArrayHelper::map($products,'id','title_uz'),
                    'pluginOptions' => [
                        'allowClear' => true,
                        // 'minimumInputLength' => 2,
                    ],
                ]);
            ?>            
        </div>
    </div>
    <div class="row">
        
        <div class="col-md-6">
            <label for="">Mahsulot narxi (so'm)</label>
            <input type="text" disabled readonly class="form-control" id='sum'>
        </div>
        <div class="col-md-6">
            <label for="">Mahsulot narxi ($)</label>
            <input type="text" disabled readonly class="form-control" id='dollar'>
        </div>
        <div class="col-md-6">
            <br>
            <?= $form->field($model, 'sale_price')->textInput() ?>
        </div>
        <div class="col-md-6">
            <br>
            <?= $form->field($model, 'sale_dollar')->textInput() ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <br>
            <?php 
                echo DateTimePicker::widget([
                    'name' => 'Section[product_sale][enter_date]',
                    'id' => 'w1',
                    'options' => ['placeholder' => 'Boshlanish vaqti', 'autocomplete' => 'off'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd hh:ii',
                        'autoclose'=>true,
                    ]
                ]);
            ?>
        </div>
        <div class="col-md-6">
            <br>
            <?php 
                echo DateTimePicker::widget([
                    'name' => 'Section[product_sale][end_date]',
                    'id' => 'w2',
                    'options' => ['placeholder' => 'Tugash vaqti', 'autocomplete' => 'off'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd hh:ii',
                        'autoclose'=>true,
                    ]
                ]);
            ?>
        </div>
    </div>
    <br>
    <div class="form-group">
        <?= Html::submitButton('Saqlash', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>


<?php
    $js = <<<JS

        $(document).on("change","#productsale-product_id",function(){
            let input = $(this).val()
            
            $.ajax({
                    url: '/product-sale/find',
                    dataType: 'json',
                    type: 'get',
                    data: {input: input},
                    success: function(response) {
                        if (response.status == 'success') {
                            $("#sum").val(response.sum)
                            $("#dollar").val(response.dollar)
                        }
                    }
                })
            
        })

    JS;
    $this->registerJs($js);
?>

views/product-sale/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProductSale */

$this->title = 'Chegirma berish';
$this->params['breadcrumbs'][] = ['label' => 'Product Sales', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-sale-create">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
        'products' => $products
    ]) ?>

</div>

views/product-sale/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Chegirmalar';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-sale-index">
    <div class="row">
        <div class="col-md-6">
            <h1 style="margin: 0;"><?= Html::encode($this->title) ?></h1>
        </div>
        <div class="col-md-6">
            <p>
                <?= Html::a('Chegirma kiritish', ['create'], ['class' => 'pull-right btn btn-success']) ?>
            </p>
        </div>
    </div>



    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [ 
                'label'  => 'Mahsulot nomi:',
                'value' => function ($data) {
                    return  $data->product->title_uz;
                }
            ],
            [ 
                'label'  => 'Chegirma summasi:',
                'value' => function ($data) {
                    return  number_format($data->sale_price,0," "," ")." so'm";
                }
            ],
            [ 
                'label'  => 'Chegirma foizi',
                'value' => function ($data) {
                    return round($data->sale_pracent);
                }
            ],
            [ 
                'label'  => 'Chegirma boshlanish vaqti',
                'value' => function ($data) {
                    return $date = date("Y-m-d H:i",strtotime($data->enter_date));
                }
            ],
            [ 
                'label'  => 'Chegirma tugash vaqti',
                'value' => function ($data) {
                    return $date = date("Y-m-d H:i",strtotime($data->end_date));
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template'=>'{update} {delete}'
            ],
        ],
    ]); ?>


</div>

views/product-sale/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProductSale */

$this->title = 'Chegirmani o`zgartirish: ' . $model->title_uz;
?>
<div class="product-sale-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'products' => $products
    ]) ?>

</div>