models/ArriveOrders.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "arrive_orders".
 *
 * @property int $id
 * @property int|null $order_code_id
 * @property int|null $product_id
 * @property int|null $sell_price
 * @property int|null $count
 */
class ArriveOrders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'arrive_orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['order_code_id', 'product_id', 'sell_price', 'count'], 'default', 'value' => null],
            [['order_code_id', 'product_id', 'sell_price', 'count'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_code_id' => 'Order Code ID',
            'product_id' => 'Product ID',
            'sell_price' => 'Sell Price',
            'count' => 'Count',
        ];
    }
    public function getProducts()
    {
        return $this->hasOne(Products::className(), ['id' => 'product_id']);
    }
    // public function getDetails()
    // {
    //     return $this->hasMany(OrderDetails::className(),['order_id' => 'order_id']);
    // }
}

models/OrderCode.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "order_code".
 *
 * @property int $id
 * @property string|null $order_code
 * @property string|null $created_date
 * @property int|null $stage
 * @property int|null $client_id
 * @property string|null $order_date
 * @property int|null $address_id
 * @property int|null $delivery_price
 * @property int|null $delivery
 * @property string|null $description
 * @property string|null $description_ru
 * @property int|null $pay
 * @property int|null $billing_status
 * @property int|null $bot
 */
class OrderCode extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_code';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_date', 'order_date'], 'safe'],
            [['stage', 'client_id', 'address_id', 'delivery_price', 'delivery', 'pay', 'billing_status', 'bot'], 'default', 'value' => null],
            [['stage', 'client_id', 'address_id', 'delivery_price', 'delivery', 'pay', 'billing_status', 'bot'], 'integer'],
            [['description', 'description_ru'], 'string'],
            [['order_code'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_code' => 'Order kodi',
            'created_date' => 'Buyurtma qilingan sana',
            'stage' => 'Etap',
            'client_id' => 'client ismi',
            'order_date' => 'Order Date',
            'address_id' => 'Address ID',
            'delivery_price' => 'Delivery Price',
            'delivery' => 'Delivery',
            'description' => 'Description',
            'description_ru' => 'Description Ru',
            'pay' => 'Pay',
            'pay' => 'To`lov turi',
            'file_id' => 'file id',
            'billing_status' => 'To`lov holati',
            'bot' => 'Bot',
        ];
    }
    public function getOrders()
    {
        return $this->hasMany(ArriveOrders::class, ['order_code_id' => 'order_code']);
    }
    public function getAddress()
    {
        return $this->hasOne(OrderAddress::className(), ['order_code_id' => 'order_code']);
    }
    public function getClient()
    {
        return $this->hasOne(Clients::className(), ['id' => 'client_id']);
    }
    public function getTotal()
    {
        $order_code = $this->order_code;
        $model = ArriveOrders::find()->where("order_code_id = :order_code",[":order_code"=>$order_code])->sum("sell_price");
        return $model;
    }
    public function getRegion()
    {
        return $this->hasOne(Region::className(), ['id' => 'region_id']);
        // return $model->title_uz;
    }

    public function getCamment()
    {
        return $this->hasOne(ClientOrderCamments::className(), ['order_code_id' => 'id']);
        // return $model->title_uz;
    }
    
}

controllers/OrderCodeController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrderCode;
use app\models\ArriveOrders;
use app\models\ClientOrderCamments;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderCodeController implements the CRUD actions for OrderCode model.
 */
class OrderCodeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();
            if (Yii::$app->user->isGuest) {
            return $this->redirect('/site/login');
        }
    }
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST','GET'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrderCode models.
     * @return mixed
     */
    public function actionIndex()
    {   
        $dataProvider = new ActiveDataProvider([
            'query' => OrderCode::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OrderCode model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {   
        $model = $this->findModel($id);
        // echo "<pre>";
        // foreach ($model->orders as $key => $value) {
        //     foreach ($value->details as $key2 => $value2) {
        //         foreach($value2->multidetails as $key3 => $value3) {
        //             print_r($value3);
        //             // echo $value3["title_uz"] . "<br>" ;
        //         }
        //     }

        // }
        // pre($model->orders);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new OrderCode model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new OrderCode();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing OrderCode model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing OrderCode model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model2 = ArriveOrders::find()->where('order_code_id = :order_code_id',[":order_code_id" => $id])->all();
        // foreach ($model2 as $value) {
        //     $value->delete();
        // }
        if ($model->delete()) {
            return $this->redirect(["index"]);
        }
    }
    public function actionConfirm($id)
    {
        
        $model = $this->findModel($id);

        $chat_id = $model->client["chat_id"];
        if (isset($chat_id) && !empty($chat_id)) {

            function bot($method, $data = []){
                $url = 'https://api.telegram.org/bot1975190483:AAHZBeqUbPWr3UXvjiSC9rSenjRBF69jFDM/'.$method;
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                $res = curl_exec($ch);

                if(curl_error($ch))
                {
                 var_dump(curl_error($ch));   
                }
                else{
                    return json_decode($res);
                }
            }

            $get_result = bot('sendMessage',[
                'chat_id' => $chat_id,
                'text' => "Sizning buyurtmangiz qabul qilindi!\nTez orada siz bilan aloqaga chiqamiz"
            ]);
            // pre();
            if ($get_result->ok === true) {
                $model->billing_status = 5;
                if ($model->save()) {
                    $this->redirect(["index"]);
                }
            }

        } else {
            echo "Chat id is empty";
            die();
        }
    }

    public function actionCheck($id)
    {
        $model = $this->findModel($id);

        $chat_id = $model->client["chat_id"];
        if (isset($chat_id) && !empty($chat_id)) {

            function bot($method, $data = []){
                $url = 'https://api.telegram.org/bot1975190483:AAHZBeqUbPWr3UXvjiSC9rSenjRBF69jFDM/'.$method;
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                $res = curl_exec($ch);

                if(curl_error($ch))
                {
                 var_dump(curl_error($ch));   
                }
                else{
                    return json_decode($res);
                }
            }

            $get_result = bot('sendMessage',[
                'chat_id' => $chat_id,
                'text' => "Sizning buyurtmangiz tasdiqlandi!\nTez orada siz bilan aloqaga chiqamiz"
            ]);
            // pre();
            if ($get_result->ok === true) {
                $model->billing_status = 6;
                if ($model->save()) {
                    $this->redirect(["index"]);
                }
            }

        } else {
            echo "Chat id is empty";
            die();
        }
    }
    public function actionWay($id)
    {
        $model = $this->findModel($id);

        $chat_id = $model->client["chat_id"];
        if (isset($chat_id) && !empty($chat_id)) {

            function bot($method, $data = []){
                $url = 'https://api.telegram.org/bot1975190483:AAHZBeqUbPWr3UXvjiSC9rSenjRBF69jFDM/'.$method;
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                $res = curl_exec($ch);

                if(curl_error($ch))
                {
                 var_dump(curl_error($ch));   
                }
                else{
                    return json_decode($res);
                }
            }

            $get_result = bot('sendMessage',[
                'chat_id' => $chat_id,
                'text' => "Sizning Buyurtmangiz yo`lga chiqdi!\nTez orada siz bilan aloqaga chiqamiz"
            ]);
            // pre();
            if ($get_result->ok === true) {
                $model->billing_status = 7;
                if ($model->save()) {
                    $this->redirect(["index"]);
                }
            }

        } else {
            echo "Chat id is empty";
            die();
        }
    }
    public function actionDone($id)
    {
        $model = $this->findModel($id);

        $chat_id = $model->client["chat_id"];
        if (isset($chat_id) && !empty($chat_id)) {

            function bot($method, $data = []){
                $url = 'https://api.telegram.org/bot1975190483:AAHZBeqUbPWr3UXvjiSC9rSenjRBF69jFDM/'.$method;
                $ch = curl_init();
                curl_setopt($ch, CURLOPT_URL, $url);
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
                curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
                $res = curl_exec($ch);

                if(curl_error($ch))
                {
                 var_dump(curl_error($ch));   
                }
                else{
                    return json_decode($res);
                }
            }
            $clb_camment = "camment_".$id;
            $order_camment_btn = json_encode([
                'inline_keyboard' =>[
                    [
                        [
                            'callback_data' => $clb_camment,
                            'text'=> "✉️ Xabar yuborish"
                        ],
                        
                    ],
                ]
            ]);

            $get_result = bot('sendMessage',[
                'chat_id' => $chat_id,
                'text' => "Sizning Buyurtmangiz yetkazib berildi!\nTez orada siz bilan aloqaga chiqamiz.Bu yurtma haqida fikringizni bildirishingizni so`rab qolamiz!",
                'reply_markup' => $order_camment_btn
            ]);
            if ($get_result->ok === true) {
                $model->billing_status = 8;
                if ($model->save()) {
                    $this->redirect(["index"]);
                }
            }

        } else {
            echo "Chat id is empty";
            die();
        }
    }

    /**
     * Finds the OrderCode model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrderCode the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrderCode::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/order-code/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OrderCode */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-code-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'order_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_date')->textInput() ?>

    <?= $form->field($model, 'stage')->textInput() ?>

    <?= $form->field($model, 'client_id')->textInput() ?>

    <?= $form->field($model, 'order_date')->textInput() ?>

    <?= $form->field($model, 'address_id')->textInput() ?>

    <?= $form->field($model, 'delivery_price')->textInput() ?>

    <?= $form->field($model, 'delivery')->textInput() ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'description_ru')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'pay')->textInput() ?>

    <?= $form->field($model, 'billing_status')->textInput() ?>

    <?= $form->field($model, 'bot')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Saqlash', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order-code/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OrderCode */

$this->title = 'Create Order Code';
$this->params['breadcrumbs'][] = ['label' => 'Order Codes', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-code-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order-code/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Buyurtmalar';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-code-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'order_code',
            [ 
                'attribute' =>'full_name',
                'label'  => ' Buyurtma vaqti',
                'value' => function ($data) {
                    return $date = date("Y-m-d H:i",strtotime($data->created_date));
                }
            ],
            [ 
                'attribute' =>'full_name',
                'label'  => 'Ismi',
                'value' => function ($data) {
                    return base64_decode($data->client->full_name);
                }
            ],
            [ 
                'attribute' =>'full_name',
                'label'  => 'Telefon raqami',
                'value' => function ($data) {
                    return base64_decode($data->client->phone_number);
                }
            ],
            [
                'format' => 'html',
                'label' => 'Holat',
                'value' => function ($data) {
                    if ($data->billing_status == 1) {
                        return '<span class=\'badge\' style=\'background:#17a2b8;\'>Buyurtma rasmiylashtiridi</span>';
                    } else if ($data->billing_status == 2) {
                        return '<span class=\'badge badge->secondary\'>Kutilmoqda</span>';
                    } else if ($data->billing_status == 3) {
                        return '<span class=\'badge badge->secondary\' >Kutilmoqda</span>';
                    } else if ($data->billing_status == 4) {
                        return '<span class=\'badge\' style=\'background:#28a745;\'>Tolov bo`lgan</span>';
                    } else if ($data->billing_status > 5) {
                        return '<span class=\'badge\' style=\'background:#28a745;\'>Qabul qilingan</span>';
                    } else  {
                        return '<span class=\'badge badge->secondary\'>Kutilmoqda</span>';
                    }
                },
            ],
            [
                'format' => 'html',
                'label' => 'Qo`shimcha',
               'contentOptions' => ['style' => 'text-align:right;'], // For TD
                'value' => function ($data) {
                    if ($data->billing_status == 1) {
                        return '<a href="/order-code/delete?id='.$data->id.'" class="btn btn-danger btn-xs"><i class="fa fa-times" aria-hidden="true"></i></a>';
                    } else if ($data->billing_status == 2) {
                        return '<a href="/order-code/delete?id='.$data->id.'" class="btn btn-danger btn-xs"><i class="fa fa-times" aria-hidden="true"></i></a>';
                    } else if ($data->billing_status == 3) {
                        return '<a href="/order-code/delete?id='.$data->id.'" class="btn btn-danger btn-xs"><i class="fa fa-times" aria-hidden="true"></i></a>';
                    } else if ($data->billing_status == 4) {
                        if ($data->type == 1 or $data->type == 2 or $data->type == 3) {
                            return '
                            <a href="/order-code/confirm?id='.$data->id.'" class="btn btn-success btn-xs">
                                Qabul qilish
                            </a>
                            <a href="/order-code/delete?id='.$data->id.'" class="btn btn-danger btn-xs">
                                <i class="fa fa-times" aria-hidden="true"></i>
                            </a>';
                        } else {
                            return '<a href="/order-code/confirm?id='.$data->id.'" class="btn btn-success btn-xs">
                                Qabul Qilish
                            </a>';

                        }
                    } else if ($data->billing_status == 5) {
                        return '<a href="/order-code/check?id='.$data->id.'" class="btn btn-success btn-xs">
                                Tasdiqlash
                            </a>';
                    } else if ($data->billing_status == 6) {
                        return '<a href="/order-code/way?id='.$data->id.'" class="btn btn-success btn-xs">
                            Yo`lga chiqarish
                        </a>';
                    } else if ($data->billing_status == 7) {
                        return '<a href="/order-code/done?id='.$data->id.'" class="btn btn-success btn-xs">
                            Yetkazib berildi
                        </a>';
                    } else if ($data->billing_status == 8) {
                        return '<span class=\'badge\' style=\'background:#28a745;\'>Buyurtma yakunlangan</span>';
                    } else {
                        return '<a href="/order-code/delete?id='.$data->id.'" class="btn btn-danger btn-xs"><i class="fa fa-times" aria-hidden="true"></i></a>';
                    }
                },
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template'=>'{view}',   
            ],
        ],
    ]); ?>


</div>

views/order-code/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OrderCode */

$this->title = 'Update Order Code: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Order Codes', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="order-code-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order-code/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\OrderCode */

$this->title = $model->order_code;
\yii\web\YiiAsset::register($this);

?>
<div class="order-code-view">

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">
            Buyurtma kodi: <?= Html::encode($this->title) ?>
        </h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <table class="table table-bordered">
            <tr>
                <th style="width: 10px">#</th>
                <th>Mahsulot nomi</th>
                <th>Buyurtma ummumiy summasi</th>
                <th>Buyurtma soni</th>
                <!-- <th>Qo`shimcha ma`lumotlar</th> -->
            </tr>
            <?php 
                $i = 1;
                foreach ($model->orders as $key => $value) { 
            ?>
                <tr>
                    <td><?php echo $i; ?></td>
                    <td><?php echo (($value->products) ? $value->products->title_uz : ''); ?></td>
                    <td><?php echo $value["sell_price"]; ?></td>
                    <td><?php echo $value["count"]; ?></td>
                    
                </tr>
            <?php
                $i++; 
                } 
            ?>
        </table>
        <div class="row">
            <div class="col-md-6">
                <?php if ($model->type == 1 ) { ?>
                    <img style="width:500px;" src="<?php echo $model->file_id ?>" alt="">
                <?php  } else if ($model->type == 2) { ?>
                    <a href="<?php echo $model->file_id; ?>" style="margin-top: 20px;" class="btn btn-success">To`lovni ko`rish</a>
                <?php } else if ($model->type == 3) { ?>
                    <p>Naqd</p>
                <?php } ?>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
    </div>
<!-- /.box -->
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <tr>
                    <!-- <th style="width: 10px">#</th> -->
                    <th>Buyurtma viloyati</th>
                    <th>Buyurtma haqida mijoz fikri</th>
                </tr>
                <tr>

                    <td><?php echo $model->region->title_uz; ?></td>
                    <?php if (isset($model->camment)): ?>
                        <td><?php echo base64_decode($model->camment->text_camment); ?></td>
                    <?php endif ?>
                    
                </tr>
            </table>            
        </div>
        <div class="col-md-12">
            <iframe src="https://maps.google.com/maps?q=<?php echo $model->lat; ?>, <?php echo $model->lang; ?>&z=15&output=embed" width="100%" height="270" frameborder="0" style="border:0"></iframe>

        </div>
    </div>
</div>